version: '3'
services:
    nginx:
        image: nginx:latest
        restart: always
        volumes:
            - ../:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8090:80"
        links:
            - php
    php:
        image: php:7-fpm
        volumes:
            - ../:/code